# Generated by Django 4.1.3 on 2022-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='exit', upload_to='images'),
            preserve_default=False,
        ),
    ]
