# Generated by Django 4.1.3 on 2022-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Место встречи', 'verbose_name_plural': 'Место встречи'},
        ),
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['location', 'title'], 'verbose_name': 'Встречи', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['id'], 'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
